server:
  port: 8080
  servlet:
    context-path: /

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: admin

  # rabbitMq 配置
  rabbitmq:
    host: localhost
    port: 5672
    #该用户不允许远程IP登录
    username: guest
    password: guest
    virtual-host: /LeslieHost

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

  #在log日志中打印
logging:
  level:
    com.example.demo.mapper: debug

  #在控制台上打印sql语句(spring boot集成mybatis的方式打印sql)
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

   #单机配置
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    password:
    port: 6379
    timeout: 30000

demo:
  swagger:
    enable: true

#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    timeout: 1000  # 连接超时时间（毫秒）
#    pool:
#      max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 20  # 连接池中的最大空闲连接
#      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      min-idle: 0 # 连接池中的最小空闲连接

  #Redis Cluster
#  redis:
#    database: 0
#    timeout: 3000
#    password: artisan
#      #  sentinel:    #哨兵模式
#    #  master: mymaster #主服务器所在集群名称
#    #  nodes: 192.168.18.131:26379,192.168.18.132:26379,192.168.18.133:26379
#    cluster:
#      nodes: 192.168.18.131:8001, 192.168.18.131:8004,  192.168.18.132:8002 ,192.168.18.132:8005, 192.168.18.133:8003 ,192.168.18.133:8006
#    lettuce:
#      pool:
#        max-idle: 50
#        min-idle: 10
#        max-active: 100
#        max-wait: 1000

  #mybatis
#  mybatis:
#    type:
#      aliases:
#        package: com.example.demo.entity